<template>
    <div>
        <DashboardListMaster 
            :model="'blog'"
            :masterEndpoint="'moderator/blogs/?submission='"
            :storeState="'halamanBlog'"
            :storeCommit="'setHalamanBlog'"
            :targetId="'blogId'"
            :targetTitle="'judulArtikel'"
            :targetLog="'logBlog'"
        />
    </div>
</template>
