<template>
    <div>
        <DashboardListMaster 
            :model="'program'"
            :masterEndpoint="'moderator/programs/?submission='"
            :storeState="'halamanProgram'"
            :storeCommit="'setHalamanProgram'"
            :targetId="'programId'"
            :targetTitle="'judulActivity'"
            :targetLog="'logProgram'"
        />
    </div>
</template>
