<template>
    <div>
        <DashboardListMaster
            :model="'event'" 
            :masterEndpoint="'moderator/events/?submission='"
            :storeState="'halamanEvent'"
            :storeCommit="'setHalamanEvent'"
            :targetId="'eventId'"
            :targetTitle="'judulActivity'"
            :targetLog="'logEvent'"
        />
    </div>
</template>
