<template>
    <div>
        <DashboardListMaster 
            :model="'resource'"
            :masterEndpoint="'moderator/resources/?submission='"
            :storeState="'halamanResource'"
            :storeCommit="'setHalamanResource'"
            :targetId="'resourceId'"
            :targetTitle="'judulArtikel'"
            :targetLog="'logResource'"
        />
    </div>
</template>
